const echarts = equire([
  // 写上你需要的
  "bar",
  "legend",
  "title",
  "line",
  "tooltip",
  "grid",
  "axisPointer",
  "pie"
  // @chart
  // "bar",
  // "boxplot",
  // "candlestick",
  // "chord",
  // "custom",
  // "effectScatter",
  // "funnel",
  // "gauge",
  // "graph",
  // "heatmap",
  // "line",
  // "lines",
  // "map",
  // "parallel",
  // "pictorialBar",
  // "pie",
  // "radar",
  // "sankey",
  // "scatter",
  // "themeRiver",
  // "treemap",
  // // @component
  // "angleAxis",
  // "axis",
  // "axisPointer",
  // "brush",
  // "calendar",
  // "dataZoom",
  // "dataZoomInside",
  // "dataZoomSelect",
  // "geo",
  // "graphic",
  // "grid",
  // "gridSimple",
  // "legend",
  // "markArea",
  // "markLine",
  // "markPoint",
  // "parallel",
  // "parallelAxis",
  // "polar",
  // "radar",
  // "radiusAxis",
  // "singleAxis",
  // "timeline",
  // "title",
  // "toolbox",
  // "tooltip",
  // "visualMap",
  // "visualMapContinuous",
  // "visualMapPiecewise"
]);

export default echarts;
